export const CHANGE_BOARD = 'BOARD/CHANGE_BOARD';
export const CHANGE_TURN = 'PLAYER/CHANGE_TURN';
export const CHANGE_PLAYERS = 'PLAYER/CHANGE_PLAYERS';
export const SET_ERROR = 'ERROR/SET_ERROR';
export const CLEAR_ERROR = 'ERROR/CLEAR_ERROR';
export const RESTART_START_NEW_GAME = 'BOARD/RESTART_START_NEW_GAME';
export const SET_WINNER = 'WINNER/SET_WINNER';
